using System;
using System.Diagnostics;
using System.IO;
using System.Runtime.InteropServices;

// Include the PDF Generator.
using PhantomJs.NetCore;

namespace ConsoleApplication
{
    public class ExampleProgram
    {
        private static readonly string _currentDirectory;
        private static readonly string _phantomJsRootFolder;
        private static readonly IPdfGenerator _generator;

        static ExampleProgram()
        {
            _currentDirectory = Directory.GetCurrentDirectory();
            _phantomJsRootFolder = Path.Combine(_currentDirectory, "PhantomJsRoot");
            _generator = new PdfGenerator(new PdfGeneratorOptions(_phantomJsRootFolder));
        }
        public static void Main(string[] args)
        {
            BasicHtmlTest();
            WithInlineStyles();
            WithRelativeStyleSheet();
            Console.ReadLine();
        }

        private static void WithRelativeStyleSheet()
        {
            var htmlToConvert =
@"
<!DOCTYPE html>
<html>
<head>
    <title>complex-test</title>
    <link href=""assets/css/pdf-styles.css"" rel=""stylesheet"" />
</head>
<body>
    <h1>Hello World!</h1>
    <p>This PDF has been generated by PhantomJs ;)</p>

    <h2>This is a subtitle</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dignissim sit amet erat vehicula semper. In lobortis, velit mattis sagittis accumsan, erat nisl tincidunt dui, varius imperdiet elit lacus non metus. Ut iaculis maximus semper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut ac pharetra augue. Fusce vitae felis auctor, rutrum urna vitae, sagittis nibh. Curabitur in aliquet odio, non varius orci. Aenean sit amet rutrum nibh. Aenean erat urna, efficitur id maximus a, dapibus ut sem.</p>
</body>
</html>
";
            ConvertHtml(htmlToConvert);
        }

        private static void WithInlineStyles()
        {
            var htmlToConvert =
@"
<!DOCTYPE html>
<html>
<head>
    <title>complex-test</title>
    <style>
        body {
            color: #333;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }

        h1 {
            background: #ff0000;
        }
    </style>
</head>
<body>
    <h1>Hello World!</h1>
    <p>This PDF has been generated by PhantomJs ;)</p>

    <h2>This is a subtitle</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dignissim sit amet erat vehicula semper. In lobortis, velit mattis sagittis accumsan, erat nisl tincidunt dui, varius imperdiet elit lacus non metus. Ut iaculis maximus semper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut ac pharetra augue. Fusce vitae felis auctor, rutrum urna vitae, sagittis nibh. Curabitur in aliquet odio, non varius orci. Aenean sit amet rutrum nibh. Aenean erat urna, efficitur id maximus a, dapibus ut sem.</p>
</body>
</html>
";
            ConvertHtml(htmlToConvert);
        }

        private static void BasicHtmlTest()
        {
            var htmlToConvert =
@"
<!DOCTYPE html>
<html>
<head>

</head>
<body>
    <h1>Hello World!</h1>
    <p>This PDF has been generated by PhantomJs ;)</p>
</body>
</html>
";
            // Generate pdf from html and place in the current folder.
            ConvertHtml(htmlToConvert);
        }

        private static void ConvertHtml(string htmlToConvert)
        {
            var pathOftheGeneratedPdf = _generator.GeneratePdf(htmlToConvert, _currentDirectory);
            Console.WriteLine("Pdf generated at: " + pathOftheGeneratedPdf);
        }
    }
}
